In [1]:
import numpy as np

In [17]:
a = np.random.randint(10, size=(5,2))
print(a)

[[9 2]
 [1 4]
 [8 7]
 [2 2]
 [9 0]]


In [6]:
a[:,0]>2

array([False,  True,  True,  True,  True])

In [11]:
a[a[:,0]>2,0] = 99

In [12]:
print(a)

[[ 1  3]
 [99  6]
 [99  5]
 [99  0]
 [99  0]]


In [18]:
b=a[:,0]>2
print(b)

[ True False  True False  True]


In [14]:
np.sum(b)

4

In [15]:
a = 2; b=5; c=1;

np.array

In [19]:
a[b,0]

array([9, 8, 9])